name: Download Cache and Create Gist

on:
  push:
    branches:
      - main  # Menjalankan workflow setiap ada push ke branch main
  workflow_dispatch:  # Allow manual triggering

jobs:
  create-gist:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Set up GitHub CLI
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Instaloader and Other
      run: |
        sudo apt-get install -y gh

      # Step 2: Restore cache (Download the latest-stamps-ini from cache)
    - name: Restore cache
      id: restore-cache
      uses: actions/cache@v3
      with:
        path: ~/.config/instaloader/latest-stamps.ini
        key: latest-stamps-ini # Ganti dengan kunci cache yang sesuai
        restore-keys: |
          latest-stamps-ini

    # Step 3: Check if cache exists
    - name: Verify if cache exists
      run: |
        if [ -f ~/.config/instaloader/latest-stamps.ini ]; then
          echo "Cache file exists."
        else
          echo "Cache file does not exist."
          exit 1
        fi

    # Step 4: Create Gist from the cache file
    - name: Create Gist from cache file
      # Pastikan GH_TOKEN sudah diset sebagai secret
      run: |
        echo "Creating Gist..."
        echo "${{ secrets.GH_TOKEN }}" | gh auth login --with-token
        # Membuat gist dengan isi file terbaru dari cache
        gh gist create ~/.config/instaloader/latest-stamps.ini --filename latest-stamps.ini -d "Latest Instagram Reels stamps"
