name: Archive New Instagram Reels to Telegram

on:
  schedule:
    - cron: '0 17 * * *'  # Runs at 17:00 UTC daily
  workflow_dispatch:  # Allows manual triggering

jobs:
  archive:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Instaloader and Other
      run: |
        pip install instaloader
        pip install python-telegram-bot
        
    - name: Download Instagram Session File
      env:
        SESSION_URL: ${{ secrets.INSTALOADER_SESSION_URL }}
      run: |
        mkdir -p ~/.config/instaloader
        curl -L "$SESSION_URL" -o ~/.config/instaloader/session-traroze

    - name: Restore cache for latest-stamps.ini
      id: cache
      uses: actions/cache@v3
      with:
        path: ~/.config/instaloader/latest-stamps.ini
        key: latest-stamps-${{ github.run_id }}  # Use a more stable cache key
        restore-keys: |
          latest-stamps-

    - name: Decode Cookies File
      run: echo "$INSTAGRAM_COOKIES_FILE" > ~/.config/instaloader/cookies.txt

    - name: Archive New Instagram Reels
      run: |
        instaloader \
          --login traroze \
          --reels \
          --no-video-thumbnails \
          --latest-stamps ~/.config/instaloader/latest-stamps.ini \
          --no-captions --no-metadata-json --no-profile-pic \
          --dirname-pattern=./downloads/:user \
          --user-agent "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" \
          gek_gandari

    - name: Upload Videos to Telegram
      run: |
          # Ganti dengan token bot Telegram dan chat ID Anda
          TELEGRAM_BOT_TOKEN="7619947662:AAHPlW2JCyOMz4aKmr_LKpNLWRG4FGFlf14"
          TELEGRAM_CHAT_ID="-1002337280272"

          # Direktori tempat video disimpan (menggunakan folder yang benar)
          DOWNLOADS_DIR="./downloads/"

          # Loop melalui semua file video di direktori
          for video in "$DOWNLOADS_DIR"/*; do
            if [[ -f "$video" && ( "$video" == *.mp4 || "$video" == *.avi || "$video" == *.mov || "$video" == *.mkv ) ]]; then
              echo "Mengupload video: $video"
              curl -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendDocument" \
                -F chat_id=$TELEGRAM_CHAT_ID \
                -F document=@"$video" \
                -F caption="Video: $(basename $video)"
            fi
          done
      
    - name: Save cache for latest-stamps.ini
      if: steps.cache.outputs.cache-hit != 'true'
      uses: actions/cache@v3
      with:
        path: ~/.config/instaloader/latest-stamps.ini
        key: latest-stamps-${{ github.run_id }}  # Use a more stable cache key
